# Generated by Django 3.1.3 on 2022-09-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20220922_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(default=None, related_name='category', to='video.Category'),
        ),
    ]
